void string_to_upper(char *str);
void string_to_lower(char *str);
void string_terminate_at_first_newline(char *str);
int string_is_empty(char *str);
void string_strip_leading_whitespace(char *str);
void field_input_init(struct field_input *field);
void address_book_entry_init(struct address_book_entry *entry);
void app_config_init(struct app_config *config);
void app_init(struct app *app);
int app_log_open(struct app *app, char *logFile);
void app_log_open_handle(struct app *app, FILE *logHandle);
void app_log_close(struct app *app);
void app_logv(struct app *app, const char *format, va_list args);
void app_logf(struct app *app, const char *format, ...);
void app_printf(struct app *app, const char *format, ...);
void print_address_book_entry(struct app *app, struct address_book_entry *entry);
int validate_address_book_name(struct field_input *field);
int validate_address_street_address(struct field_input *field);
int validate_address_city(struct field_input *field);
int validate_address_province(struct field_input *field);
int validate_address_postal_code(struct field_input *field);
int validate_address_phone_number(struct field_input *field);
void collect_wait_for_key(void);
int collect_field_input(struct app *app, struct field_input *field);
int collect_address_book_entry(struct app *app, struct address_book_entry *currentEntry);
void collect_address_book(struct app *app);
void print_address_book(struct app *app);
int main(void);
